printf(
"Suricata Configuration:\n"
"  AF_PACKET support:                       yes\n"
"  PF_RING support:                         no\n"
"  NFQueue support:                         yes\n"
"  IPFW support:                            no\n"
"  DAG enabled:                             no\n"
"  Napatech enabled:                        no\n"
"  Unix socket enabled:                     yes\n"
"  Detection enabled:                       yes\n"
"\n"
"  libnss support:                          no\n"
"  libnspr support:                         no\n"
"  libjansson support:                      yes\n"
"  Prelude support:                         no\n"
"  PCRE jit:                                yes\n"
"  libluajit:                               no\n"
"  libgeoip:                                no\n"
"  Non-bundled htp:                         yes\n"
"  Old barnyard2 support:                   no\n"
"  CUDA enabled:                            no\n"
"\n"
"  Suricatasc install:                      yes\n"
"\n"
"  Unit tests enabled:                      no\n"
"  Debug output enabled:                    yes\n"
"  Debug validation enabled:                no\n"
"  Profiling enabled:                       no\n"
"  Profiling locks enabled:                 no\n"
"  Coccinelle / spatch:                     no\n"
"\n"
"Generic build parameters:\n"
"  Installation prefix (--prefix):          /usr/local\n"
"  Configuration directory (--sysconfdir):  /usr/local/etc/suricata/\n"
"  Log directory (--localstatedir) :        /usr/local/var/log/suricata/\n"
"\n"
"  Host:                                    i686-pc-linux-gnu\n"
"  GCC binary:                              gcc\n"
"  GCC Protect enabled:                     no\n"
"  GCC march native enabled:                yes\n"
"  GCC Profile enabled:                     no\n"
);
